services:
  frontend:
    container_name: g6_dev_frontend
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
    volumes:
      - /app/node_modules
      - ./client:/app
    restart: unless-stopped
  
  backend:
    container_name: g6_dev_backend
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    env_file:
     - .env
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - ./server:/app
      - ~/.nuget/packages:/root/.nuget/packages:ro
    restart: unless-stopped
  postgres:
    container_name: postgres
    image: postgres:17.6
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata: