FROM mcr.microsoft.com/dotnet/sdk:9.0-alpine3.21

WORKDIR /app

# Copier uniquement les fichiers de projet (pour le restore)
COPY Gunpla_600.API/Gunpla_600.API.csproj Gunpla_600.API/
COPY Gunpla_600.Application/Gunpla_600.Application.csproj Gunpla_600.Application/
COPY Gunpla_600.Domain/Gunpla_600.Domain.csproj Gunpla_600.Domain/
COPY Gunpla_600.Infrastructure/Gunpla_600.Infrastructure.csproj Gunpla_600.Infrastructure/

RUN dotnet restore Gunpla_600.API/Gunpla_600.API.csproj

COPY . .

EXPOSE 5000

ENTRYPOINT [ "dotnet", "watch", "run", "--project", "Gunpla_600.API/Gunpla_600.API.csproj" ]